WithMarks(StudentId) :-
	Marks(StudentId, CourseId, Mark),
	Courses(CourseId, CourseName),
	CourseName = :CourseName.

WithPlan(GroupId) :-
	Plan(GroupId, CourseId, LecturerId),
	Courses(CourseId, CourseName),
	CourseName = :CourseName.	

StudentsInfo(StudentId, StudentName, GroupName) :-
	Students(StudentId, StudentName, GroupId),
	Groups(GroupId, GroupName, GroupFacultyId),
	not WithMarks(StudentId),
	WithPlan(GroupId).

