version: '3.8'

services:
  maria-db:
    image: mariadb:10.11
    container_name: maria-db
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - db_data_ctd:/var/lib/mysql
      - ./database/initdb.d:/docker-entrypoint-initdb.d

  pma:
    image: phpmyadmin/phpmyadmin:5.2.1
    restart: always
    ports:
      - "3086:80"
    depends_on:
      - maria-db
    environment:
      PMA_HOST: maria-db
      PMA_USER: root
      PMA_PASSWORD: root


volumes:
  db_data_ctd:
